### ISSUE TITLE
Issues starting on linux

### ISSUE THREAD

**Issue by CleanItWithWub** [cesar-rgon/simple-kf2-server-launcher#1]
Hi, as the title says the .jar is not running on my Ubuntu box.

I'm currently running on Ubuntu 18.04, with a fresh install of Oracle Java 11. The zip file has been extracted to a folder on my desktop, and when I attempt to run with the command "java -jar SimpleKF2ServerLauncher.jar" I get the error

Error: Could not find or load main class start.MainApplication
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

I love the idea of making an easy way to get a KF2 server up and going please keep it up.

**Comment by cesar-rgon** [comment]
Hi.
It seems that problem is caused by the application don't know who is the starting class to be launched.
Sorry, when i develope under IDE all works fine and I didn't notice that problem.
I'm going to fix it as soon as posible.
Stay alert, i will tell you here when new release will be available.
Regards.

**Comment by cesar-rgon** [comment]
Hi.
I have Ubuntu 19.04 instead of Ubuntu 18.04 but i think this should not be a problem.
I have made it work as follows:

Follow these steps:
1. Download Oracle JRE from here: https://www.java.com/en/download/ (Linux x64, or the apropiate for your system)

2. Extract the content of the tar.gz file to a local folder, for example: /home/yourUser/jre1.8.0_221

3. Define the apropiate JAVA_HOME and PATH for your system:
$ sudo gedit /etc/profile
(Add at the end of the file next lines)
export JAVA_HOME="/home/yourUser/jre1.8.0_221"
export PATH=$JAVA_HOME/bin:$PATH
(Replace folder names to your needs. Save and exit)

4. Close session or restart the system.

5. Open a console and type: java -version
Check if the correct version is displayed.

6. If all goes well, the application should be started running:
java -jar SimpleKF2ServerLauncher.jar

I hope everything works correctly.
Regards.
