### ISSUE TITLE
Custom maps are not present in the map cycle when the server is launch from any profile other than default.

### ISSUE THREAD

**Issue by ghost** [cesar-rgon/simple-kf2-server-launcher#2]
There seems to be way to choose the map cycle before launching. I would like to see a feature where one can choose the map list before the server is launched. 
![image](https://user-images.githubusercontent.com/33142754/62899301-d0f76c00-bd9a-11e9-8015-2372c74e032a.png)

**Comment by cesar-rgon** [comment]
Hi.
Are you using the last release of the launcher?
I have fixed this in the last version: actually v2.0_beta_190811

I can not reproduce the problem. If I create two profiles, custom maps are present in map cycle for both profiles.

If you already have the last version can you tell me with more details what have you done?

Thank you very much for your feedback.

BTW, good idea about the feature to select maps of mapcycle in the launcher. I will implement it for a future release.

**Comment by ghost** [comment]
While trying for about 5 hours to see if the problem was fixed or not I discovered that if you include a mutators to the custom maps, it will launch once and one the second launch it will crash the server and corrupt the profile. By the looks of it the map list is fixed.

**Comment by ghost** [comment]
It's possible to download the mutators to a client and then copy the files into the server however this solution is not ideal.

**Comment by cesar-rgon** [comment]
Hi.
You're right. That solution is not ideal at all.

I'm improving the launcher to have a good integration with MOD's installation, for example, with mutators. Thouse changes will be available for next release that i will public in a few days.

At this moment, with the actual version, mods are supported but the launcher has a bad integration with them. I explain myself, you can follow next steps to install a mutator in the server:

- Search in WorkShop the mutator and add it to the launcher (press button "Add map").

- Now you should see in maps menu the mutator with state "Start server to download it".

- Start the server and wait some minutes until the mutator is downloaded (Item state 4 in server console). You should see a new folder in KFGame\Cache\idWorkShop of the mutator in the server's local folder. Then you actually knows that the mutator is really installed in the server.

- Close the server and go to the maps menu.

- The mutator state is still "Start server to download it", why? because it's not a map, the launcher only identify downloaded maps in this version (not mods), but in fact, the mutator is really downloaded.

- Put mutators params in custom parameters of main page (be careful to not start the list of params with ?, the launcher automatically add it to console) (i will fix that in next release to support params that start with ? as well as not start with ?)

- Run the server and the mutator should be there, it should be work.

No need to copy the mutators from client to server, the mutator is installed automatically in KFGame\Cache folder of the server.


About the problem that you reported, the server crushes and the profile was corrupted, can you send me the file "launcher.log"? It's located in your launcher's local folder. With logs i can see the error and try to fix it for next release.

Thank you very much for your feedback, that help me to improve the application.

Regards.

**Comment by ghost** [comment]
So I was getting two types of errors. The first type was where the launcher wouldn't let me attempt a launch. The second error was when it would launch but crash instantly.
[error.txt](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3503384/error.txt)

Here is the launcher log.
[launcher.log](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3503383/launcher.log)

PS Thank you very much for your friendliness and hard work

**Comment by cesar-rgon** [comment]
Hi Isaac.
I have developed and published a new release of the launcher.
For this version, is recommended to start with a fresh installation of the launcher and database.

All you have to do is:
	- Define the location of the KF2's server.
	- Use the import funtionality (in maps page) to check and import to the launcher all maps and mods present in your server.

Mod integration is completed, so you can see now what is a mod and what is a map in the launcher.
Logs are more verbose to help me find bugs.

Let me know your feedback again.

Thank you and regards.

**Comment by ghost** [comment]
This is brilliant. Good work.
There was one map that didn't get imported. I'm not bothered by it but no loss in letting you know.
Error [launcher.log](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3512507/launcher.log)

A few features I would like to see:
  Being able to import and duplicate profiles.
  Choosing a workshop items per profile.
  Launching multiple profiles at once.
 
Thank you very much for your work. Sorry if I come across as demanding.

**Comment by cesar-rgon** [comment]
Ok. I'm going to check if something is wrong with that map. I can see id workshop in logs.
Thanks for reporting it.

About the new features yo are talking about:

- To export and import profiles could be interesting. I think you refer export from the launcher to a file and import from a file to the launcher, isn't it?

- To duplicate profiles should be easy to implementate. Good idea.

- To choose workshop items per profile implies changes in database, so it would be a no retro-compatible update, that means that you must start the upgrade with a fresh install of the launcher and database, starting your configuration from zero. But the launcher is still beta... major changes should be done now, not in final release. Of course it is interesting too.

- To launch multiple profiles. I'm thinking about to launch multiple servers through console commands. Something like:
java -jar SimpleKF2Server.jar --profiles profileName1, profileName2, ...
Are you thinking the same? Or something different?

I'm going to write all your sugestions in the TODO document located in the wiki section of Github.

https://github.com/cesar-rgon/simple-kf2-server-launcher/wiki/Functionalities-to-do-and-bugs-to-be-fixed-for-the-next-realeases

Thank you very much Isaac.

**Comment by cesar-rgon** [comment]
Hi.
I have developed and published a new release of the launcher.

This release has many new features like:

- Duplicate profiles.
- Import profiles from a file.
- Export profiles to a file.
- Launch multiple profile at once.
- etc (See release changelog:)
https://github.com/cesar-rgon/simple-kf2-server-launcher/releases/tag/2.0_beta_190822

- I will develope the feature: WorkShop items per profile in a future release.

Regards.

**Comment by ghost** [comment]
Yes. This is great. Very good job. I'm all out of suggestions at
the moment. I'll let you know if I come up with anything that might be
useful. Thank you very much for making such a useful application.
