### ISSUE TITLE
Error when importing profile from different version

### ISSUE THREAD

**Issue by ghost** [cesar-rgon/simple-kf2-server-launcher#3]
I got 3 errors when I tried to import a profile from beta version 190822 to the latest version 190905.
It then gave me the option of what profiles I want to add, followed by an other error. Non of the profiles were add.

First three errors: 
[error1](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3586370/pf190822to190905_1.txt) 
[error2](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3586371/pf190822to190905_2.txt) 
[error3](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3586372/pf190822to190905_3.txt)

Last [error](https://github.com/cesar-rgon/simple-kf2-server-launcher/files/3586369/pf190822to190905_4.txt)

The reason why I updated versions is because I was having issues where if I launched the server with the new beta map or nuked obj, the map list would not show up when every died. I checked the map cycle in web admin and it seemed to be filled it with everything. 

Another issue is that the new map wouldn't show up in the 'change map' section in the web admin. My guess is that it wasn't been properly written in the PCServer-KFGame file.

**Comment by cesar-rgon** [comment]
Hi Isaac.

- About the issue of import/export profiles:

It seems that the launcher can't import maximum players configuration because it has a not standard value.
If that is the case, be sure to follow next steps:

**Launcher version 190822**
1. Select standard values in all combos. For example, max.players: 6
2. Export needed profiles

**Launcher version 190905**
1. Define installation folder
2. Import custom maps/mods
3. Import profiles (exported from version 190822)


If the problem persist, could you send me the exported file to be sure what is happening?


- About the issue with map cycle in beta version of Killing Floor 2

That is not a problem of the launcher, it is a problem of the kf2's beta itself.
I have reported the issue in Tripwire's discord, i think it should be solved soon. Perhaps with the next kf2's beta update.


- About not showing new map in WebAdmin page.

You're right, the new map should have entries in PCServer-KFGame.ini file.
I'm going to report the problem in Tripwire's Discord too.

Thank you for your feedback
Regards

**Comment by cesar-rgon** [comment]
Hi.
A beta update of Killing Floor 2 has been published, i think beta 2.
I have seen that the issue of maps cycle has been fixed. Now you can vote maps again.
Furthermore the map Ashwood Asylum is available in the maps combo of WebAdmin page.

I'm developing v2.0 final release of the launcher.

This release will have maps per profiles and an improvement with export/import profiles to avoid errors when you have selected not standard values in some combos (like game types, maps, difficulties, etc).

Regards.

![20190918220656_1](https://user-images.githubusercontent.com/4352939/65187333-9355c500-da63-11e9-93ef-462ace67739b.jpg)

**Comment by ghost** [comment]
Wonderful. Thanks for the update. Love your work and I'm looking forward to
your next release.

**Comment by cesar-rgon** [comment]
Hi Isaac.
Final version of the launcher is finally here :)

I hope you can find it useful.
Regards.
